captainVersion: 4
services:
    $$cap_appname:
        image: eclipse-mosquitto:$$cap_app_version
        volumes:
            - $$cap_appname-eclipse-config:/mosquitto/config/
            - $$cap_appname-eclipse-data:/mosquitto/data/
            - $$cap_appname-eclipse-log:/mosquitto/log/
        ports: []
        restart: always
        caproverExtra:
            notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - id: $$cap_app_version
          label: Eclipes-Mosquitto Image Version
          defaultValue: '2'
          validRegex: /^([^\s^\/])+$/
          description: The version of the Eclipes-Mosquitto image to use. Check https://hub.docker.com/_/eclipse-mosquitto/tags for available versions.
    instructions:
        start: Eclipse Mosquitto is an open source message broker which implements MQTT version 5, 3.1.1 and 3.1. Enter Parameters below
        end: Eclipes-Mosquitto is deployed and available as srv-captain--$$cap_appname:1883 to other apps and srv-captain--$$cap_appname:9001 as a websocket.
    displayName: Eclipse Mosquitto - A MQTT Broker
    isOfficial: true
    description: Eclipse Mosquitto is an open source message broker which implements MQTT version 5, 3.1.1 and 3.1
    documentation: Taken from https://github.com/eclipse/mosquitto. Mosquitto is an open source implementation of a server for version 5.0, 3.1.1, and 3.1 of the MQTT protocol. It also includes a C and C++ client library, and the mosquitto_pub and mosquitto_sub utilities for publishing and subscribing.
